### ISSUE TITLE
Child process for opponent AI exiting with code 255.

### ISSUE THREAD

**Issue by Superman8218** [dramamine/leftovers-again#10]
When I try to run
`npm start -- --opponent=randumb`
I get the response
`child process for randumb exited with code 255`

**Comment by dramamine** [comment]
OK, this was due to nickname collisions - I think someone registered some of the default bot names which is causing lots of login problems.
(Exit code 255 usually happens because "nickname is already registered")

The long-term solution is to mock the login server (instead of always using the official login server). However I added a hacky fix to 0.11.4 which will just add random numbers to the end of nicknames if they're already registered.
If you run `npm install leftovers-again@latest` you should get this update.

https://github.com/dramamine/leftovers-again/commit/dc0d22b1dfcc21e7db8e446064807a3ff46e25fd

**Comment by Superman8218** [comment]
So I had it working for a little bit, but now whenever I run the same line of code, it just freezes.  Your "hacky fix" is working, but something else is causing the battles to not run.  When I connect with my local browser I'm seeing the bots are logged into the server, but no battles are being run.

**Comment by dramamine** [comment]
Hmm hmm. Can you try running `npm start -- --opponent=randumb --loglevel=5` and see what the last few lines are?

**Comment by Superman8218** [comment]
```
Not challenging {my bot} because that's me
sending team msg...
sending challenge... larandumbbot8173 gen7ou
updated challenges: {"challengesFrom":{}, "challengeTo":{"to":"larandumbbot8173","format":gen7out"}}
```

And if I run 
`npm start --stabby --opponent=randumb --loglevel=5`
then I don't get any of those log messages.  So that's notable to I suppose

**Comment by Superman8218** [comment]
FYI I plan to hack together a way for your project to support Python, relying on Node's child process module.  I've already got proof of concept working.  I'll just have to formalize it.

**Comment by dramamine** [comment]
Cool! Python support sounds great =)
I think your dashes on that second command look wrong, I would try:
`npm start -- stabby --opponent=randumb --loglevel=5`
Otherwise it treats stabby as a flag instead of a bot name.

Something suspicious about those challenge lines is that it says "format":gen7out" but it should be "gen7ou". Not sure why it's like that but on the line before it says gen7ou. Maybe try playing around with that, fixing a typo or trying to run a different format like "ou" or "anythinggoes"?

**Comment by Superman8218** [comment]
So the `gen7out` thing was just a typo.  You're right that I was missing a space though.  So now when I run it with the stabby bot name I get just the exact same output as when I run it and try to use my own bot

**Comment by dramamine** [comment]
Hmm I'm kind of lost, not able to repro. When I run this:
```
$ ~/git/leftovers-again
 $ npm start -- stabby --opponent=randumb --loglevel=5
```
I get:
```
Got open message from server's websocket.
Successfully logged in as la-stabbystabs2584 (lastabbystabs2584)
Not challenging lastabbystabs2584 because that's me.
sending challenge... larandumbbot6985 gen7randombattle
updated challenges: {"challengesFrom":{},"challengeTo":{"to":"larandumbbot6985","format":"gen7randombattle"}}
updated challenges: {"challengesFrom":{},"challengeTo":null}
no outstanding challenges.
Match started! lastabbystabs2584 vs. larandumbbot6985
Your team is: Whimsicott, Jirachi, Noctowl, Abomasnow, Aromatisse, Kecleon
```

**Comment by Superman8218** [comment]
Alright I'll keep investigating and post what I find
