### ISSUE TITLE
When the bot's Pokémon faints, how do I get the bot to calculate which Pokémon on their team is most effective against my current Pokémon and switch accordingly?

### ISSUE THREAD

**Issue by BeyondTheHorizon** [dramamine/leftovers-again#21]
Hi, I don't want my bot to switch to a random Pokémon upon their current Pokémon fainting. How do I program it to calculate which Pokémon on their team is most effective against my current Pokémon and switch accordingly? Thanks for reading.

**Comment by dramamine** [comment]
In the request you'll find that state.forceSwitch is true. There's some more info about that here:
https://github.com/dramamine/leftovers-again/blob/master/FAQ.md

In the demo bot we are calling the function "pickOne" to pick a random bot - instead of using pickOne, you should write your own function to determine which Pokemon you want to bring out.
https://github.com/dramamine/leftovers-again/blob/master/src/bots/stabby/stabby.js

**Comment by BeyondTheHorizon** [comment]
Thanks for the reply, but since I'm a complete amateur at programming I don't really know exactly what to write. I want to initiate a battle with a bot that uses the three Kanto starters and battle it with the same team, for testing purposes. If I KO'd the bot's Venusaur with my own Venusaur, exactly what should I code to make certain it would send out Charizard next, which is strong against Venusaur? Sorry for my complete ignorance in programming.

**Comment by dramamine** [comment]
I mean, I can't help you write your code, but the info you need is available to you! The `state.opponent.active` object is going to have the species property you're looking for, for example.

**Comment by BeyondTheHorizon** [comment]
Oh. Okay, I'll have a try.
